### ISSUE TITLE
HU1 Landing Page (Login)

### ISSUE THREAD

**Issue by Taniagf31** [ConyGage/DEV002-notes#2]

**Comment by Taniagf31** [comment]
pagina de iniciar sesión en Google

**Comment by Taniagf31** [comment]
> 1. Hacer primeros pasos en CSS para visualizar la página deseada (colores, tipo de letra img, etc).
> ![Image](https://user-images.githubusercontent.com/111469309/213329816-68abaa6b-ec53-4023-bb41-9c2cbd88121c.jpeg)
> 2. Ver videos de David recomendados. [https://www.youtube.com/watch?v=bvxm389cYVI](url) [https://www.youtube.com/watch?v=cHKCQPDpCgQ&list=PLJubkp8BnTJskTj7EFmJV4X3t8u2JOFso](url) https://www.youtube.com/watch?v=cHKCQPDpCgQ&list=PLJubkp8BnTJskTj7EFmJV4X3t8u2JOFso
> 3. Ver video de React (Udemy) tiempo 54 hrs. Acceso a Udemy...
Correo: floresalvarado.alicia@gmail.com
Constraseña: Nomeacuerdo1
> https://www.youtube.com/playlist?list=PL3aEngjGbYhkg3AR-cytsvQIIGp1JgrY_
> 4. Ver nivel de video e implementarlo en código.
> 5. Gym (practica de 3 ejercicios JS, CSS, REACT).

**Comment by ConyGuGa** [comment]
#11
